<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DarkRiftLibPath Condition="'$(DarkRiftLibPath)' == ''">$(MSBuildThisFileDirectory)..\NiftyClubServerCore\Lib</DarkRiftLibPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DarkRift">
      <HintPath>$(DarkRiftLibPath)\DarkRift.dll</HintPath>
    </Reference>
    <Reference Include="DarkRift.Server">
      <HintPath>$(DarkRiftLibPath)\DarkRift.Server.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <PluginDestination Include="$(MSBuildThisFileDirectory)..\NiftyClubServer\Plugins" />
      <PluginDestination Include="$(MSBuildThisFileDirectory)..\NiftyClubServerCore\Plugins" />
    </ItemGroup>
    <MakeDir Directories="@(PluginDestination)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="%(PluginDestination.Identity)" />
  </Target>

</Project>
